name: ESlint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Setup depends
      run: npm install
    - name: check with eslint
      run: npx eslint .
